name: Tools build for Windows

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install pkg
      run: npm i -g pkg
    - name: Generate webfilesbuilder binaries
      run: |
        cd tools/webfilesbuilder
        npm install
        pkg -t node16-win -C GZip .
    - name: Generate wsemulator binaries
      run: |
        cd tools/wsemulator
        npm install
        pkg -t node16-win -C GZip .

    - name: Export Windows binary
      uses: actions/upload-artifact@v2
      with:
        name: bins
        path: |
          tools/webfilesbuilder/webfilesbuilder.exe
          tools/wsemulator/wsemulator.exe
